GET  http://localhost:3000/ HTTP/1.1
###
GET  http://localhost:3000/users/ HTTP/1.1
###
POST http://localhost:3000/users HTTP/1.1
content-type: application/json 

{
    "email": "marcos.henrique@toptal.com",
    "password": "sup3rS3cr3tPassw0rd!23",
    "name": "Marcoss"
}
###
GET http://localhost:3000/users/1
###
DELETE http://localhost:3000/users/2 HTTP/1.1
###
PUT http://localhost:3000/users/1
Content-Type: application/json

{
    "email": "marcos.henrique@toptal.com",
    "password": "sup3rS3cr3tPassw0rd!23",
    "name": "Marcoss Frontier",
    "permissionLevel": 8
}