GET  http://localhost:3000/ HTTP/1.1
###
GET  http://localhost:3000/users/ HTTP/1.1
###
POST http://localhost:3000/users HTTP/1.1
content-type: application/json 

{
    "email": "marcos.henrique@toptal.com",
    "password": "sup3rS3cr3tPassw0rd!23"
}
###
GET http://localhost:3000/users/WK1_ue7gNXBKxl1TTWYWD
###
DELETE http://localhost:3000/users/WK1_ue7gNXBKxl1TTWYWD HTTP/1.1
###
PUT http://localhost:3000/users/WtLNikIKdzXNijmqrW8ka
Content-Type: application/json

{
    "email": "marcos.henrique@toptal.com",
    "password": "sup3rS3cr3tPassw0rd!23",
    "firstName": "Marcoss",
    "lastName": "Silva",
    "permissionLevel": 8
}'